export enum QuestionType {
  FETCH_QUESTIONS_LIST_REQUEST = 'FETCH_QUESTIONS_LIST_REQUEST',
  FETCH_QUESTIONS_LIST_SUCCESS = 'FETCH_QUESTIONS_LIST_SUCCESS',
  FETCH_QUESTIONS_LIST_FAILURE = 'FETCH_QUESTIONS_LIST_FAILURE'
}
